# Generated by Django 4.2 on 2023-05-07 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_padaria', '0003_clientes_delete_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clientes',
            new_name='Cliente',
        ),
    ]
