# Generated by Django 4.2.1 on 2024-01-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_padaria', '0006_alter_recebimento_status_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
                ('quantidade_estoque', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('disponivel', models.BooleanField(default=True, editable=False, verbose_name='Disponível')),
            ],
        ),
    ]
